name: clipp_conductor
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.18+23


environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  socket_io_client: ^1.0.2
  shared_preferences: ^2.0.15
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  page_transition: ^2.0.9
  dots_indicator: ^2.0.0
  dotted_line: ^3.0.0
  audioplayers: ^4.1.0
  crypto: ^3.0.1
  auto_size_text: ^3.0.0
  permission_handler: ^10.4.3
  geolocator: ^10.1.0
  flutter_tts: ^3.8.5
  slide_to_confirm: ^1.1.0
  dio: ^4.0.0
  rflutter_alert: ^2.0.4
  vector_math: ^2.1.2
  intl: ^0.18.0
  url_launcher: ^6.2.2
  reviews_slider: ^2.0.0
  timezone: ^0.9.0
  webview_flutter: ^4.2.2
  location: ^5.0.3
  battery_info: ^1.1.1
  image_picker: ^0.8.7+1
  path_provider: ^2.0.15
  speech_to_text: ^6.1.1
  speech_to_text_platform_interface: ^2.0.1
  speech_to_text_macos: ^1.0.2
  custom_sliding_segmented_control: ^1.7.4
  month_picker_dialog: ^2.4.0
  siri_wave: ^1.0.0
  audio_wave: ^0.1.5
  audio_waveforms: ^1.0.4
  archive: ^3.3.7
  flutter_animate: ^4.2.0+1
  ripple_wave: ^0.1.3
  story_view: ^0.16.0
  transparent_image: ^2.0.0
  connectivity_plus: ^3.0.6
  numeric_keyboard: ^1.1.0
  badges: ^3.1.2
  wakelock_plus: ^1.1.4
  intl_phone_number_input: ^0.7.0+2
  flutter_facebook_auth: ^4.4.1+1
  delayed_display: ^2.0.0
  flutter_timezone: ^1.0.7
  google_maps_flutter_android: ^2.5.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_platform_interface: ^2.4.0
  flutter_plugin_android_lifecycle: ^2.0.1
  loading_animation_widget: ^1.2.0+2
  loading_indicator: ^3.1.1
  google_sign_in: ^6.1.5
  firebase_auth: ^4.11.1
  firebase_core: ^2.18.0
  dash_bubble: ^2.0.0
  flutter_foreground_task: '>=6.1.0'
  platform: ^3.1.1
  plugin_platform_interface: ^2.1.6
  http: '>=0.13.5'
  flutter_image_compress: ^2.1.0
  another_flushbar: ^1.12.30
  widget_and_text_animator: ^1.1.5
  sign_in_with_apple: ^5.0.0
  flutter_blue_plus: ^1.30.3
  app_settings: ^5.1.1
  app_version_update: ^4.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_randomcolor: ^1.0.14
  hexcolor: ^3.0.1
  share_plus: ^7.2.2
  google_mlkit_face_detection: ^0.9.0
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  build_runner: ^2.1.10
  espresso: ^0.2.0
  flutter_test:
    sdk: flutter
  #  integration_test:
  #    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/splash/
    - assets/audio/warning.mp3
    - assets/audio/alarm.mp3
    - assets/audio/no_service.mp3
    - assets/audio/notice_arrival.mp3
    - assets/audio/start_service.mp3
    - assets/audio/send_chat.mp3
    - assets/audio/alert.mp3
    - assets/maps/style_map_day.json
    - assets/maps/style_map_night.json

  fonts:
    - family: title
      fonts:
        - asset: assets/fonts/title.otf
    - family: subTitle
      fonts:
        - asset: assets/fonts/subTitle.otf